version: '3.7'
services:
    demoapp-ws:
        image: priyakdey/springboot-demo-app:1.1
        ports:
            - 9080:8080
        depends_on:
            - demoapp-db
        environment:
            - spring.datasource.url=jdbc:mysql://demoapp-db:3306/sample_db?createDatabaseIfNotExist=true
    demoapp-db:
        image: mysql:latest
        ports:
            - "3306:3306"
            - "33060:33060"
        volumes:
            - "/Users/priyakdey/Projects/Docker/db_data_mount:/var/lib/mysql"
        environment:
            - MYSQL_ROOT_PASSWORD=priyakdey
